# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajout_voiture.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QMessageBox

from PyQt5 import QtCore, QtGui, QtWidgets
from voiture import voiture
from agence import agence    
class Ui_ajout_voiture(object):
   
    def __init__(self,agence):
        self.ag = agence
    
    def succ(self,str):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText(str)
        msgBox.setWindowTitle("Ajout reussie")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec_()
    
    def warn(self,str):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Warning)
        msgBox.setText(str)
        msgBox.setWindowTitle("Msg Error")      
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec_()
    
    
    def remplir(self):            
        if(self.ag.verif_mat(self.lineEdit.text())==False):
            self.warn("la matricule doit etre sous la forme : *tn*")
        elif(self.lineEdit_2.text()==""):
            self.warn("Marque invalide")
        elif(self.ag.verif_coul(self.lineEdit_3.text())==False or self.lineEdit_3.text()==""):
            self.warn("couleur invalide")
        elif(self.lineEdit_4.text()=="" or self.lineEdit_4.text().isnumeric()==False):
            self.warn("Prix invalide")
        elif(self.ag.verif_date(self.lineEdit_5.text())==False):
            self.warn("La date doit etre sous la forme 01/01/2000")
        else:
            v = voiture(self.lineEdit.text(),self.lineEdit_2.text(),self.lineEdit_3.text(),self.lineEdit_5.text(),self.lineEdit_4.text()) 
            self.ag.ajout_voiture(v.l)
            self.succ("Voiture ajoutée avec succés")
            self.lineEdit.setText("");
            self.lineEdit_2.setText("");
            self.lineEdit_3.setText("");
            self.lineEdit_4.setText("");
            self.lineEdit_5.setText("");
            

        
    def setupUi(self, ajout_voiture):
        ajout_voiture.setObjectName("ajout_voiture")
        ajout_voiture.resize(371, 443)
        ajout_voiture.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        ajout_voiture.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(ajout_voiture)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 381, 421))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 371, 401))
        self.label.setStyleSheet("border-image: url(:/images/back_ajout_voiture.jpg);\n"
"border-radius:7px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 371, 401))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,180); \n"
"border-radius:7px; ")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 231, 31))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(11)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color :rgba(255,255,255,0.7)")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(70, 290, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(20,47,78,219),stop:1 rgba(85,98,112,226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(40,67,98,219),stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(20,47,78,219),stop:1 rgba(85,98,112,226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:5px;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 350, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(20,47,78,219),stop:1 rgba(85,98,112,226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(40,67,98,219),stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(20,47,78,219),stop:1 rgba(85,98,112,226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:5px;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 80, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :rgba(255,255,255,230);\n"
"padding-bottom:7px ;")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 120, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :rgba(255,255,255,230);\n"
"padding-bottom:7px ;")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 150, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :rgba(255,255,255,230);\n"
"padding-bottom:7px ;")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(60, 190, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :rgba(255,255,255,230);\n"
"padding-bottom:7px ;")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 240, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :rgba(255,255,255,230);\n"
"padding-bottom:7px ;")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        
        ajout_voiture.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ajout_voiture)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 22))
        self.menubar.setObjectName("menubar")
        ajout_voiture.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ajout_voiture)
        self.statusbar.setObjectName("statusbar")
        ajout_voiture.setStatusBar(self.statusbar)

        self.retranslateUi(ajout_voiture)
        QtCore.QMetaObject.connectSlotsByName(ajout_voiture)
        
        self.pushButton.clicked.connect(self.remplir)

          
    def retranslateUi(self, ajout_voiture):
        _translate = QtCore.QCoreApplication.translate
        ajout_voiture.setWindowTitle(_translate("ajout_voiture", "MainWindow"))
        self.label_3.setText(_translate("ajout_voiture", "Ajouter voiture"))
        
        self.pushButton.setText(_translate("ajout_voiture", "Ajouter"))   
          

        self.pushButton_2.setText(_translate("ajout_voiture", "Annuler"))
        self.pushButton_2.clicked.connect(ajout_voiture.close)  
        self.lineEdit.setPlaceholderText(_translate("ajout_voiture", "Matricule"))
        self.lineEdit_2.setPlaceholderText(_translate("ajout_voiture", "Marque"))
        self.lineEdit_5.setPlaceholderText(_translate("ajout_voiture", "Date"))
        self.lineEdit_3.setPlaceholderText(_translate("ajout_voiture", "Couleur"))
        self.lineEdit_4.setPlaceholderText(_translate("ajout_voiture", "Prix de location"))
    
import res_ajout_voiture


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ajout_voiture = QtWidgets.QMainWindow()
    ui = Ui_ajout_voiture()
    ui.setupUi(ajout_voiture)
    ajout_voiture.show()
    sys.exit(app.exec_())
    




