# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajout_loc.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import * 
from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import * 
from PyQt5.QtCore import * 
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

import datetime
import time
from PyQt5.QtWidgets import QMessageBox
from location import location
from agence import agence

class Ui_Form(object):
    def __init__(self,agence):
        self.ag = agence
        self.l=[]

    def succ(self,str):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText(str)
        msgBox.setWindowTitle("Ajout reussie")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec_()
    
    def warn(self,str):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Warning)
        msgBox.setText(str)
        msgBox.setWindowTitle("Msg Error")      
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec_()
  
    def verif_date(self,d1,ch):
        newdate1 = time.strptime(d1, "%d/%m/%Y %H:%M")
        
        for i in self.ag.liste_loc:
            if i[2]==ch:
                date_2 = time.strptime(str(i[3]), "%d/%m/%Y %H:%M")
                date_1 = datetime.datetime.strptime(str(i[3]), "%d/%m/%Y %H:%M")
                d3=str(date_1 + datetime.timedelta(days=int(i[4])))
                
                dfi=d3[8]+d3[9]+"/"+d3[5]+d3[6]+"/"+d3[0]+d3[1]+d3[2]+d3[3]+ " " + d3[11]+d3[12]+d3[13]+d3[14]+d3[15]
                df=time.strptime(dfi, "%d/%m/%Y %H:%M")
                if(df>newdate1>=date_2):
                    return False
        return True
    
    def remplir(self):
        vt = self.comboBox.currentText()
        ch=""
        for i in vt:
            if i==" ":
                break
            else:
                ch=ch+i
        v = self.ag.rechercher_voiture(ch)
        
        if(self.ag.cin_valide(self.lineEdit_4.text())==False):
            self.warn("cin invalide")
        elif (self.comboBox.currentText() == "choisir une voiture"):
            self.warn("Veuillez choisir une voiture")
        elif(self.verif_date(self.dateTimeEdit.text(),ch)==False):
            self.warn("Voiture reservé dans cette date")
        elif(self.lineEdit_6.text().isnumeric()==False):
            self.warn("durée invalide")
        else:
            c = location(len(self.ag.liste_loc)+1,self.lineEdit_4.text(),ch,self.dateTimeEdit.text(),self.lineEdit_6.text(),int(self.lineEdit_6.text())*int(self.ag.get_prix(ch)))
            self.ag.change_loc(ch)
            self.ag.ajout_loc(c.l)
            self.succ("Location ajouté avec succées")
            self.comboBox.setCurrentIndex(0)
            self.lineEdit_6.setText("")
            self.lineEdit_4.setText("")
            d = QDateTime(2000, 1, 1, 00, 00)
            self.dateTimeEdit.setDateTime(d)
            
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(510, 450)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 511, 451))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 511, 451))
        self.label.setStyleSheet("border-image: url(:/images/abstract-gradient-blue-to-white-sq-format-thomas-woolworth.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 511, 451))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,180); \n"
"border-radius:7px; ")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 291, 31))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color :rgba(255,255,255,0.7)")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(70, 160, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :rgba(255,255,255,1);\n"
"padding-bottom:7px ;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 110, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :white;\n"
"padding-bottom:7px ;")
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(220, 220, 221, 41))
        self.dateTimeEdit.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :rgba(255,255,255,1);\n"
"padding-bottom:7px ;")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(230, 280, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :white;\n"
"padding-bottom:7px ;")
        self.lineEdit_6.setPlaceholderText("")
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(140, 360, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(20,47,78,0.6),stop:1 rgba(85,98,112,0.6));\n"
"color:rgba(255,255,255,0.6);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(40,67,98,219),stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0  rgba(20,47,78,0.6),stop:1 rgba(85,98,112,0.6));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:5px;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 400, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(20,47,78,0.6),stop:1 rgba(85,98,112,0.6));\n"
"color:rgba(255,255,255,0.6);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_3:hover{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(40,67,98,219),stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#pushButton_3:pressed{\n"
"background-color : qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0  rgba(20,47,78,0.6),stop:1 rgba(85,98,112,0.6));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:5px;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(70, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :white;\n"
"padding-bottom:7px ;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(70, 220, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :white;\n"
"padding-bottom:7px ;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(70, 280, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none ;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color :white;\n"
"padding-bottom:7px ;")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        self.pushButton.clicked.connect(self.remplir)
        self.pushButton_3.clicked.connect(Form.close)  
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Ajouter une nouvelle location"))
        self.comboBox.setItemText(0, _translate("Form", "choisir une voiture"))
        self.pushButton.setText(_translate("Form", "Ajouter"))
        self.pushButton_3.setText(_translate("Form", "Fermer"))
        self.label_4.setText(_translate("Form", "CIN du client :"))
        self.label_5.setText(_translate("Form", "Date de location :"))
        self.label_6.setText(_translate("Form", "Durée de location :"))
        
        for i in range(len(self.ag.liste_v)):
            self.l.append(str(self.ag.liste_v[i][0])+" "+str(self.ag.liste_v[i][1])+" "+str(self.ag.liste_v[i][2]))  

        for i in range(len(self.l)):
            self.comboBox.addItem("")
            self.comboBox.setItemText(i+1, _translate("Form",self.l[i]))
import res_msgbox_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
